# .rubocop.yml
#
# Configuration for rubocop, a static code analyzer for Ruby.
#
# https://github.com/bbatsov/rubocop#configuration

inherit_from: .rubocop_todo.yml

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/IndentHash:
  EnforcedStyle: consistent

# Style/AccessModifierIndentation
#
# Indent access modifiers like `protected` and `private`.
Style/AccessModifierIndentation:
  EnforcedStyle: indent

# Style/FileName
#
# Long, long ago, this was named with a dash rather than an underscore. Now
# it's unconventional, but let's consider it retro and leave it for now so we
# don't have to rename the gem. TODO: Rename using an underscore.
Style/FileName:
  Exclude:
    - 'lib/pandoc-ruby.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Style/IndentationConsistency
#
# Use Rails-style access modifier indentation.
#
# Example:
# ```
# class Foo
#   def bar
#     puts 'bar'
#   end
#
#   private
#
#     def baz
#       puts 'baz'
#     end
# end
# ```
Style/IndentationConsistency:
  EnforcedStyle: rails

# Style/SymbolArray
#
# Avoid `%i` syntax so symbols look like symbols.
Style/SymbolArray:
  EnforcedStyle: brackets

# Style/RedundantSelf
#
# Explicit `self` is currently preferred in this project in order to
# better distinguish between accessors and local variables.
Style/RedundantSelf:
  Exclude:
    - 'lib/pandoc-ruby.rb'
